#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 92
#define ALIAS_COUNT 0
#define TOKEN_COUNT 61
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  sym_label = 1,
  sym_comment = 2,
  anon_sym_COMMA = 3,
  anon_sym_CMP = 4,
  anon_sym_MOVE = 5,
  anon_sym_ORG = 6,
  aux_sym_define_memory_token1 = 7,
  anon_sym_EQU = 8,
  anon_sym_JP = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_JR = 12,
  anon_sym_CALL = 13,
  aux_sym_ret_token1 = 14,
  anon_sym_HALT = 15,
  anon_sym__C = 16,
  anon_sym__NC = 17,
  anon_sym__V = 18,
  anon_sym__NV = 19,
  anon_sym__N = 20,
  anon_sym__NN = 21,
  anon_sym__M = 22,
  anon_sym__P = 23,
  anon_sym__Z = 24,
  anon_sym__NZ = 25,
  anon_sym__EQ = 26,
  anon_sym__NE = 27,
  anon_sym__ULE = 28,
  anon_sym__UGT = 29,
  anon_sym__ULT = 30,
  anon_sym__UGE = 31,
  anon_sym__SLE = 32,
  anon_sym__SGT = 33,
  anon_sym__SLT = 34,
  anon_sym__SGE = 35,
  aux_sym_load_operation_token1 = 36,
  aux_sym_store_operation_token1 = 37,
  anon_sym_PLUS = 38,
  anon_sym_POP = 39,
  anon_sym_PUSH = 40,
  anon_sym_ADD = 41,
  anon_sym_ADC = 42,
  anon_sym_SUB = 43,
  anon_sym_SBC = 44,
  anon_sym_AND = 45,
  anon_sym_OR = 46,
  anon_sym_XOR = 47,
  anon_sym_SHL = 48,
  anon_sym_SHR = 49,
  anon_sym_ASHR = 50,
  anon_sym_ROTL = 51,
  anon_sym_ROTR = 52,
  aux_sym_register_token1 = 53,
  anon_sym_SP = 54,
  anon_sym_SR = 55,
  anon_sym_PC = 56,
  sym_dec = 57,
  sym_bin = 58,
  sym_oct = 59,
  sym_hex = 60,
  sym_source_file = 61,
  sym__statement = 62,
  sym_binary_operation = 63,
  sym_compare = 64,
  sym_move = 65,
  sym_memory_operation = 66,
  sym_control_operation = 67,
  sym__preprocessor = 68,
  sym_org = 69,
  sym_define_memory = 70,
  sym_equ = 71,
  sym_jump = 72,
  sym_jump_relative = 73,
  sym_call = 74,
  sym_ret = 75,
  sym_halt = 76,
  sym_condition = 77,
  sym_load_operation = 78,
  sym_store_operation = 79,
  sym_reg_offset = 80,
  sym_stack_operation = 81,
  sym_alu_mnemonic = 82,
  sym_src1 = 83,
  sym_src2 = 84,
  sym_dest = 85,
  sym_register = 86,
  sym_immediate = 87,
  sym_numbers = 88,
  sym_number = 89,
  aux_sym_source_file_repeat1 = 90,
  aux_sym_numbers_repeat1 = 91,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_label] = "label",
  [sym_comment] = "comment",
  [anon_sym_COMMA] = ",",
  [anon_sym_CMP] = "CMP",
  [anon_sym_MOVE] = "MOVE",
  [anon_sym_ORG] = "ORG",
  [aux_sym_define_memory_token1] = "define_memory_token1",
  [anon_sym_EQU] = "EQU",
  [anon_sym_JP] = "JP",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_JR] = "JR",
  [anon_sym_CALL] = "CALL",
  [aux_sym_ret_token1] = "ret_token1",
  [anon_sym_HALT] = "HALT",
  [anon_sym__C] = "_C",
  [anon_sym__NC] = "_NC",
  [anon_sym__V] = "_V",
  [anon_sym__NV] = "_NV",
  [anon_sym__N] = "_N",
  [anon_sym__NN] = "_NN",
  [anon_sym__M] = "_M",
  [anon_sym__P] = "_P",
  [anon_sym__Z] = "_Z",
  [anon_sym__NZ] = "_NZ",
  [anon_sym__EQ] = "_EQ",
  [anon_sym__NE] = "_NE",
  [anon_sym__ULE] = "_ULE",
  [anon_sym__UGT] = "_UGT",
  [anon_sym__ULT] = "_ULT",
  [anon_sym__UGE] = "_UGE",
  [anon_sym__SLE] = "_SLE",
  [anon_sym__SGT] = "_SGT",
  [anon_sym__SLT] = "_SLT",
  [anon_sym__SGE] = "_SGE",
  [aux_sym_load_operation_token1] = "load_operation_token1",
  [aux_sym_store_operation_token1] = "store_operation_token1",
  [anon_sym_PLUS] = "+",
  [anon_sym_POP] = "POP",
  [anon_sym_PUSH] = "PUSH",
  [anon_sym_ADD] = "ADD",
  [anon_sym_ADC] = "ADC",
  [anon_sym_SUB] = "SUB",
  [anon_sym_SBC] = "SBC",
  [anon_sym_AND] = "AND",
  [anon_sym_OR] = "OR",
  [anon_sym_XOR] = "XOR",
  [anon_sym_SHL] = "SHL",
  [anon_sym_SHR] = "SHR",
  [anon_sym_ASHR] = "ASHR",
  [anon_sym_ROTL] = "ROTL",
  [anon_sym_ROTR] = "ROTR",
  [aux_sym_register_token1] = "register_token1",
  [anon_sym_SP] = "SP",
  [anon_sym_SR] = "SR",
  [anon_sym_PC] = "PC",
  [sym_dec] = "dec",
  [sym_bin] = "bin",
  [sym_oct] = "oct",
  [sym_hex] = "hex",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_binary_operation] = "binary_operation",
  [sym_compare] = "compare",
  [sym_move] = "move",
  [sym_memory_operation] = "memory_operation",
  [sym_control_operation] = "control_operation",
  [sym__preprocessor] = "_preprocessor",
  [sym_org] = "org",
  [sym_define_memory] = "define_memory",
  [sym_equ] = "equ",
  [sym_jump] = "jump",
  [sym_jump_relative] = "jump_relative",
  [sym_call] = "call",
  [sym_ret] = "ret",
  [sym_halt] = "halt",
  [sym_condition] = "condition",
  [sym_load_operation] = "load_operation",
  [sym_store_operation] = "store_operation",
  [sym_reg_offset] = "reg_offset",
  [sym_stack_operation] = "stack_operation",
  [sym_alu_mnemonic] = "alu_mnemonic",
  [sym_src1] = "src1",
  [sym_src2] = "src2",
  [sym_dest] = "dest",
  [sym_register] = "register",
  [sym_immediate] = "immediate",
  [sym_numbers] = "numbers",
  [sym_number] = "number",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_numbers_repeat1] = "numbers_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_label] = sym_label,
  [sym_comment] = sym_comment,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_CMP] = anon_sym_CMP,
  [anon_sym_MOVE] = anon_sym_MOVE,
  [anon_sym_ORG] = anon_sym_ORG,
  [aux_sym_define_memory_token1] = aux_sym_define_memory_token1,
  [anon_sym_EQU] = anon_sym_EQU,
  [anon_sym_JP] = anon_sym_JP,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_JR] = anon_sym_JR,
  [anon_sym_CALL] = anon_sym_CALL,
  [aux_sym_ret_token1] = aux_sym_ret_token1,
  [anon_sym_HALT] = anon_sym_HALT,
  [anon_sym__C] = anon_sym__C,
  [anon_sym__NC] = anon_sym__NC,
  [anon_sym__V] = anon_sym__V,
  [anon_sym__NV] = anon_sym__NV,
  [anon_sym__N] = anon_sym__N,
  [anon_sym__NN] = anon_sym__NN,
  [anon_sym__M] = anon_sym__M,
  [anon_sym__P] = anon_sym__P,
  [anon_sym__Z] = anon_sym__Z,
  [anon_sym__NZ] = anon_sym__NZ,
  [anon_sym__EQ] = anon_sym__EQ,
  [anon_sym__NE] = anon_sym__NE,
  [anon_sym__ULE] = anon_sym__ULE,
  [anon_sym__UGT] = anon_sym__UGT,
  [anon_sym__ULT] = anon_sym__ULT,
  [anon_sym__UGE] = anon_sym__UGE,
  [anon_sym__SLE] = anon_sym__SLE,
  [anon_sym__SGT] = anon_sym__SGT,
  [anon_sym__SLT] = anon_sym__SLT,
  [anon_sym__SGE] = anon_sym__SGE,
  [aux_sym_load_operation_token1] = aux_sym_load_operation_token1,
  [aux_sym_store_operation_token1] = aux_sym_store_operation_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_POP] = anon_sym_POP,
  [anon_sym_PUSH] = anon_sym_PUSH,
  [anon_sym_ADD] = anon_sym_ADD,
  [anon_sym_ADC] = anon_sym_ADC,
  [anon_sym_SUB] = anon_sym_SUB,
  [anon_sym_SBC] = anon_sym_SBC,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_XOR] = anon_sym_XOR,
  [anon_sym_SHL] = anon_sym_SHL,
  [anon_sym_SHR] = anon_sym_SHR,
  [anon_sym_ASHR] = anon_sym_ASHR,
  [anon_sym_ROTL] = anon_sym_ROTL,
  [anon_sym_ROTR] = anon_sym_ROTR,
  [aux_sym_register_token1] = aux_sym_register_token1,
  [anon_sym_SP] = anon_sym_SP,
  [anon_sym_SR] = anon_sym_SR,
  [anon_sym_PC] = anon_sym_PC,
  [sym_dec] = sym_dec,
  [sym_bin] = sym_bin,
  [sym_oct] = sym_oct,
  [sym_hex] = sym_hex,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_binary_operation] = sym_binary_operation,
  [sym_compare] = sym_compare,
  [sym_move] = sym_move,
  [sym_memory_operation] = sym_memory_operation,
  [sym_control_operation] = sym_control_operation,
  [sym__preprocessor] = sym__preprocessor,
  [sym_org] = sym_org,
  [sym_define_memory] = sym_define_memory,
  [sym_equ] = sym_equ,
  [sym_jump] = sym_jump,
  [sym_jump_relative] = sym_jump_relative,
  [sym_call] = sym_call,
  [sym_ret] = sym_ret,
  [sym_halt] = sym_halt,
  [sym_condition] = sym_condition,
  [sym_load_operation] = sym_load_operation,
  [sym_store_operation] = sym_store_operation,
  [sym_reg_offset] = sym_reg_offset,
  [sym_stack_operation] = sym_stack_operation,
  [sym_alu_mnemonic] = sym_alu_mnemonic,
  [sym_src1] = sym_src1,
  [sym_src2] = sym_src2,
  [sym_dest] = sym_dest,
  [sym_register] = sym_register,
  [sym_immediate] = sym_immediate,
  [sym_numbers] = sym_numbers,
  [sym_number] = sym_number,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_numbers_repeat1] = aux_sym_numbers_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MOVE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ORG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_define_memory_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_JP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_JR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CALL] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ret_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_HALT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__NC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__V] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__NV] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__N] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__NN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__M] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__P] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__Z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__NZ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__NE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__ULE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__UGT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__ULT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__UGE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__SLE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__SGT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__SLT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__SGE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_load_operation_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_store_operation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUSH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ADD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ADC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SUB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SBC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_XOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SHL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SHR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ASHR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ROTL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ROTR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_register_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PC] = {
    .visible = true,
    .named = false,
  },
  [sym_dec] = {
    .visible = true,
    .named = true,
  },
  [sym_bin] = {
    .visible = true,
    .named = true,
  },
  [sym_oct] = {
    .visible = true,
    .named = true,
  },
  [sym_hex] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_compare] = {
    .visible = true,
    .named = true,
  },
  [sym_move] = {
    .visible = true,
    .named = true,
  },
  [sym_memory_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_control_operation] = {
    .visible = true,
    .named = true,
  },
  [sym__preprocessor] = {
    .visible = false,
    .named = true,
  },
  [sym_org] = {
    .visible = true,
    .named = true,
  },
  [sym_define_memory] = {
    .visible = true,
    .named = true,
  },
  [sym_equ] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_relative] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_ret] = {
    .visible = true,
    .named = true,
  },
  [sym_halt] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_load_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_store_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_reg_offset] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_alu_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [sym_src1] = {
    .visible = true,
    .named = true,
  },
  [sym_src2] = {
    .visible = true,
    .named = true,
  },
  [sym_dest] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_immediate] = {
    .visible = true,
    .named = true,
  },
  [sym_numbers] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_numbers_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '+') ADVANCE(45);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == ';') ADVANCE(21);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'D') ADVANCE(2);
      if (lookahead == 'O') ADVANCE(3);
      END_STATE();
    case 8:
      if (lookahead == 'C') ADVANCE(25);
      if (lookahead == 'E') ADVANCE(15);
      if (lookahead == 'M') ADVANCE(31);
      if (lookahead == 'N') ADVANCE(29);
      if (lookahead == 'P') ADVANCE(32);
      if (lookahead == 'S') ADVANCE(13);
      if (lookahead == 'U') ADVANCE(14);
      if (lookahead == 'V') ADVANCE(27);
      if (lookahead == 'Z') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(44);
      if (lookahead == 'T') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(41);
      if (lookahead == 'T') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(40);
      if (lookahead == 'T') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(37);
      if (lookahead == 'T') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == 'G') ADVANCE(9);
      if (lookahead == 'L') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'G') ADVANCE(11);
      if (lookahead == 'L') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'Q') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(49);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym__C);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym__NC);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym__V);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym__NV);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym__N);
      if (lookahead == 'C') ADVANCE(26);
      if (lookahead == 'E') ADVANCE(36);
      if (lookahead == 'N') ADVANCE(30);
      if (lookahead == 'V') ADVANCE(28);
      if (lookahead == 'Z') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym__NN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym__M);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym__P);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym__Z);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym__NZ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym__EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym__NE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym__ULE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym__UGT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym__ULT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym__UGE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym__SLE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym__SGT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym__SLT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym__SGE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_label);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_dec);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_bin);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_oct);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'A') ADVANCE(1);
      if (lookahead == 'C') ADVANCE(2);
      if (lookahead == 'D') ADVANCE(3);
      if (lookahead == 'E') ADVANCE(4);
      if (lookahead == 'H') ADVANCE(5);
      if (lookahead == 'J') ADVANCE(6);
      if (lookahead == 'L') ADVANCE(7);
      if (lookahead == 'M') ADVANCE(8);
      if (lookahead == 'O') ADVANCE(9);
      if (lookahead == 'P') ADVANCE(10);
      if (lookahead == 'R') ADVANCE(11);
      if (lookahead == 'S') ADVANCE(12);
      if (lookahead == 'X') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'D') ADVANCE(14);
      if (lookahead == 'N') ADVANCE(15);
      if (lookahead == 'S') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'A') ADVANCE(17);
      if (lookahead == 'M') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'B' ||
          lookahead == 'H' ||
          lookahead == 'S' ||
          lookahead == 'W') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'Q') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'P') ADVANCE(22);
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'O') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'O') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'R') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(27);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == 'U') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(30);
      if (lookahead == 'O') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'B') ADVANCE(33);
      if (lookahead == 'H') ADVANCE(34);
      if (lookahead == 'P') ADVANCE(35);
      if (lookahead == 'R') ADVANCE(36);
      if (lookahead == 'T') ADVANCE(37);
      if (lookahead == 'U') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'O') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == 'C') ADVANCE(40);
      if (lookahead == 'D') ADVANCE(41);
      END_STATE();
    case 15:
      if (lookahead == 'D') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'H') ADVANCE(43);
      END_STATE();
    case 17:
      if (lookahead == 'L') ADVANCE(44);
      END_STATE();
    case 18:
      if (lookahead == 'P') ADVANCE(45);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_define_memory_token1);
      END_STATE();
    case 20:
      if (lookahead == 'U') ADVANCE(46);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(47);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_JP);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_JR);
      END_STATE();
    case 24:
      if (lookahead == 'A') ADVANCE(48);
      END_STATE();
    case 25:
      if (lookahead == 'V') ADVANCE(49);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_OR);
      if (lookahead == 'G') ADVANCE(50);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PC);
      END_STATE();
    case 28:
      if (lookahead == 'P') ADVANCE(51);
      END_STATE();
    case 29:
      if (lookahead == 'S') ADVANCE(52);
      END_STATE();
    case 30:
      if (lookahead == 'T') ADVANCE(53);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(54);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_register_token1);
      END_STATE();
    case 33:
      if (lookahead == 'C') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'L') ADVANCE(56);
      if (lookahead == 'R') ADVANCE(57);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SP);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SR);
      END_STATE();
    case 37:
      if (lookahead == 'O') ADVANCE(58);
      END_STATE();
    case 38:
      if (lookahead == 'B') ADVANCE(59);
      END_STATE();
    case 39:
      if (lookahead == 'R') ADVANCE(60);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_ADC);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_ADD);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 43:
      if (lookahead == 'R') ADVANCE(61);
      END_STATE();
    case 44:
      if (lookahead == 'L') ADVANCE(62);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_CMP);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQU);
      END_STATE();
    case 47:
      if (lookahead == 'T') ADVANCE(63);
      END_STATE();
    case 48:
      if (lookahead == 'D') ADVANCE(64);
      END_STATE();
    case 49:
      if (lookahead == 'E') ADVANCE(65);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_ORG);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_POP);
      END_STATE();
    case 52:
      if (lookahead == 'H') ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_ret_token1);
      if (lookahead == 'I' ||
          lookahead == 'N') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'L') ADVANCE(68);
      if (lookahead == 'R') ADVANCE(69);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SBC);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SHL);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SHR);
      END_STATE();
    case 58:
      if (lookahead == 'R') ADVANCE(70);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_SUB);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_XOR);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ASHR);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_CALL);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_HALT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_load_operation_token1);
      if (lookahead == 'B' ||
          lookahead == 'H') ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_MOVE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_PUSH);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_ret_token1);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_ROTL);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_ROTR);
      END_STATE();
    case 70:
      if (lookahead == 'E') ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_load_operation_token1);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_store_operation_token1);
      if (lookahead == 'B' ||
          lookahead == 'H') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_store_operation_token1);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_CMP] = ACTIONS(1),
    [anon_sym_MOVE] = ACTIONS(1),
    [anon_sym_ORG] = ACTIONS(1),
    [aux_sym_define_memory_token1] = ACTIONS(1),
    [anon_sym_EQU] = ACTIONS(1),
    [anon_sym_JP] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_JR] = ACTIONS(1),
    [anon_sym_CALL] = ACTIONS(1),
    [aux_sym_ret_token1] = ACTIONS(1),
    [anon_sym_HALT] = ACTIONS(1),
    [anon_sym__C] = ACTIONS(1),
    [anon_sym__NC] = ACTIONS(1),
    [anon_sym__V] = ACTIONS(1),
    [anon_sym__NV] = ACTIONS(1),
    [anon_sym__N] = ACTIONS(1),
    [anon_sym__NN] = ACTIONS(1),
    [anon_sym__M] = ACTIONS(1),
    [anon_sym__P] = ACTIONS(1),
    [anon_sym__Z] = ACTIONS(1),
    [anon_sym__NZ] = ACTIONS(1),
    [anon_sym__EQ] = ACTIONS(1),
    [anon_sym__NE] = ACTIONS(1),
    [anon_sym__ULE] = ACTIONS(1),
    [anon_sym__UGT] = ACTIONS(1),
    [anon_sym__ULT] = ACTIONS(1),
    [anon_sym__UGE] = ACTIONS(1),
    [anon_sym__SLE] = ACTIONS(1),
    [anon_sym__SGT] = ACTIONS(1),
    [anon_sym__SLT] = ACTIONS(1),
    [anon_sym__SGE] = ACTIONS(1),
    [aux_sym_load_operation_token1] = ACTIONS(1),
    [aux_sym_store_operation_token1] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_POP] = ACTIONS(1),
    [anon_sym_PUSH] = ACTIONS(1),
    [anon_sym_ADD] = ACTIONS(1),
    [anon_sym_ADC] = ACTIONS(1),
    [anon_sym_SUB] = ACTIONS(1),
    [anon_sym_SBC] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_XOR] = ACTIONS(1),
    [anon_sym_SHL] = ACTIONS(1),
    [anon_sym_SHR] = ACTIONS(1),
    [anon_sym_ASHR] = ACTIONS(1),
    [anon_sym_ROTL] = ACTIONS(1),
    [anon_sym_ROTR] = ACTIONS(1),
    [aux_sym_register_token1] = ACTIONS(1),
    [anon_sym_SP] = ACTIONS(1),
    [anon_sym_SR] = ACTIONS(1),
    [anon_sym_PC] = ACTIONS(1),
    [sym_dec] = ACTIONS(1),
    [sym_bin] = ACTIONS(1),
    [sym_oct] = ACTIONS(1),
    [sym_hex] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym__statement] = STATE(5),
    [sym_binary_operation] = STATE(5),
    [sym_compare] = STATE(5),
    [sym_move] = STATE(5),
    [sym_memory_operation] = STATE(5),
    [sym_control_operation] = STATE(5),
    [sym__preprocessor] = STATE(5),
    [sym_org] = STATE(5),
    [sym_define_memory] = STATE(5),
    [sym_equ] = STATE(5),
    [sym_jump] = STATE(26),
    [sym_jump_relative] = STATE(26),
    [sym_call] = STATE(26),
    [sym_ret] = STATE(26),
    [sym_halt] = STATE(26),
    [sym_load_operation] = STATE(27),
    [sym_store_operation] = STATE(27),
    [sym_stack_operation] = STATE(27),
    [sym_alu_mnemonic] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_label] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_CMP] = ACTIONS(9),
    [anon_sym_MOVE] = ACTIONS(11),
    [anon_sym_ORG] = ACTIONS(13),
    [aux_sym_define_memory_token1] = ACTIONS(15),
    [anon_sym_EQU] = ACTIONS(17),
    [anon_sym_JP] = ACTIONS(19),
    [anon_sym_JR] = ACTIONS(21),
    [anon_sym_CALL] = ACTIONS(23),
    [aux_sym_ret_token1] = ACTIONS(25),
    [anon_sym_HALT] = ACTIONS(27),
    [aux_sym_load_operation_token1] = ACTIONS(29),
    [aux_sym_store_operation_token1] = ACTIONS(31),
    [anon_sym_POP] = ACTIONS(33),
    [anon_sym_PUSH] = ACTIONS(33),
    [anon_sym_ADD] = ACTIONS(35),
    [anon_sym_ADC] = ACTIONS(35),
    [anon_sym_SUB] = ACTIONS(35),
    [anon_sym_SBC] = ACTIONS(35),
    [anon_sym_AND] = ACTIONS(35),
    [anon_sym_OR] = ACTIONS(35),
    [anon_sym_XOR] = ACTIONS(35),
    [anon_sym_SHL] = ACTIONS(35),
    [anon_sym_SHR] = ACTIONS(35),
    [anon_sym_ASHR] = ACTIONS(35),
    [anon_sym_ROTL] = ACTIONS(35),
    [anon_sym_ROTR] = ACTIONS(35),
  },
  [2] = {
    [sym_condition] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_label] = ACTIONS(39),
    [sym_comment] = ACTIONS(37),
    [anon_sym_CMP] = ACTIONS(39),
    [anon_sym_MOVE] = ACTIONS(39),
    [anon_sym_ORG] = ACTIONS(39),
    [aux_sym_define_memory_token1] = ACTIONS(39),
    [anon_sym_EQU] = ACTIONS(39),
    [anon_sym_JP] = ACTIONS(39),
    [anon_sym_JR] = ACTIONS(39),
    [anon_sym_CALL] = ACTIONS(39),
    [aux_sym_ret_token1] = ACTIONS(39),
    [anon_sym_HALT] = ACTIONS(39),
    [anon_sym__C] = ACTIONS(41),
    [anon_sym__NC] = ACTIONS(41),
    [anon_sym__V] = ACTIONS(41),
    [anon_sym__NV] = ACTIONS(41),
    [anon_sym__N] = ACTIONS(43),
    [anon_sym__NN] = ACTIONS(41),
    [anon_sym__M] = ACTIONS(41),
    [anon_sym__P] = ACTIONS(41),
    [anon_sym__Z] = ACTIONS(41),
    [anon_sym__NZ] = ACTIONS(41),
    [anon_sym__EQ] = ACTIONS(41),
    [anon_sym__NE] = ACTIONS(41),
    [anon_sym__ULE] = ACTIONS(41),
    [anon_sym__UGT] = ACTIONS(41),
    [anon_sym__ULT] = ACTIONS(41),
    [anon_sym__UGE] = ACTIONS(41),
    [anon_sym__SLE] = ACTIONS(41),
    [anon_sym__SGT] = ACTIONS(41),
    [anon_sym__SLT] = ACTIONS(41),
    [anon_sym__SGE] = ACTIONS(41),
    [aux_sym_load_operation_token1] = ACTIONS(39),
    [aux_sym_store_operation_token1] = ACTIONS(39),
    [anon_sym_POP] = ACTIONS(39),
    [anon_sym_PUSH] = ACTIONS(39),
    [anon_sym_ADD] = ACTIONS(39),
    [anon_sym_ADC] = ACTIONS(39),
    [anon_sym_SUB] = ACTIONS(39),
    [anon_sym_SBC] = ACTIONS(39),
    [anon_sym_AND] = ACTIONS(39),
    [anon_sym_OR] = ACTIONS(39),
    [anon_sym_XOR] = ACTIONS(39),
    [anon_sym_SHL] = ACTIONS(39),
    [anon_sym_SHR] = ACTIONS(39),
    [anon_sym_ASHR] = ACTIONS(39),
    [anon_sym_ROTL] = ACTIONS(39),
    [anon_sym_ROTR] = ACTIONS(39),
  },
  [3] = {
    [sym_condition] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_label] = ACTIONS(47),
    [sym_comment] = ACTIONS(45),
    [anon_sym_CMP] = ACTIONS(47),
    [anon_sym_MOVE] = ACTIONS(47),
    [anon_sym_ORG] = ACTIONS(47),
    [aux_sym_define_memory_token1] = ACTIONS(47),
    [anon_sym_EQU] = ACTIONS(47),
    [anon_sym_JP] = ACTIONS(47),
    [anon_sym_JR] = ACTIONS(47),
    [anon_sym_CALL] = ACTIONS(47),
    [aux_sym_ret_token1] = ACTIONS(47),
    [anon_sym_HALT] = ACTIONS(47),
    [anon_sym__C] = ACTIONS(41),
    [anon_sym__NC] = ACTIONS(41),
    [anon_sym__V] = ACTIONS(41),
    [anon_sym__NV] = ACTIONS(41),
    [anon_sym__N] = ACTIONS(43),
    [anon_sym__NN] = ACTIONS(41),
    [anon_sym__M] = ACTIONS(41),
    [anon_sym__P] = ACTIONS(41),
    [anon_sym__Z] = ACTIONS(41),
    [anon_sym__NZ] = ACTIONS(41),
    [anon_sym__EQ] = ACTIONS(41),
    [anon_sym__NE] = ACTIONS(41),
    [anon_sym__ULE] = ACTIONS(41),
    [anon_sym__UGT] = ACTIONS(41),
    [anon_sym__ULT] = ACTIONS(41),
    [anon_sym__UGE] = ACTIONS(41),
    [anon_sym__SLE] = ACTIONS(41),
    [anon_sym__SGT] = ACTIONS(41),
    [anon_sym__SLT] = ACTIONS(41),
    [anon_sym__SGE] = ACTIONS(41),
    [aux_sym_load_operation_token1] = ACTIONS(47),
    [aux_sym_store_operation_token1] = ACTIONS(47),
    [anon_sym_POP] = ACTIONS(47),
    [anon_sym_PUSH] = ACTIONS(47),
    [anon_sym_ADD] = ACTIONS(47),
    [anon_sym_ADC] = ACTIONS(47),
    [anon_sym_SUB] = ACTIONS(47),
    [anon_sym_SBC] = ACTIONS(47),
    [anon_sym_AND] = ACTIONS(47),
    [anon_sym_OR] = ACTIONS(47),
    [anon_sym_XOR] = ACTIONS(47),
    [anon_sym_SHL] = ACTIONS(47),
    [anon_sym_SHR] = ACTIONS(47),
    [anon_sym_ASHR] = ACTIONS(47),
    [anon_sym_ROTL] = ACTIONS(47),
    [anon_sym_ROTR] = ACTIONS(47),
  },
  [4] = {
    [sym__statement] = STATE(4),
    [sym_binary_operation] = STATE(4),
    [sym_compare] = STATE(4),
    [sym_move] = STATE(4),
    [sym_memory_operation] = STATE(4),
    [sym_control_operation] = STATE(4),
    [sym__preprocessor] = STATE(4),
    [sym_org] = STATE(4),
    [sym_define_memory] = STATE(4),
    [sym_equ] = STATE(4),
    [sym_jump] = STATE(26),
    [sym_jump_relative] = STATE(26),
    [sym_call] = STATE(26),
    [sym_ret] = STATE(26),
    [sym_halt] = STATE(26),
    [sym_load_operation] = STATE(27),
    [sym_store_operation] = STATE(27),
    [sym_stack_operation] = STATE(27),
    [sym_alu_mnemonic] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_label] = ACTIONS(51),
    [sym_comment] = ACTIONS(54),
    [anon_sym_CMP] = ACTIONS(57),
    [anon_sym_MOVE] = ACTIONS(60),
    [anon_sym_ORG] = ACTIONS(63),
    [aux_sym_define_memory_token1] = ACTIONS(66),
    [anon_sym_EQU] = ACTIONS(69),
    [anon_sym_JP] = ACTIONS(72),
    [anon_sym_JR] = ACTIONS(75),
    [anon_sym_CALL] = ACTIONS(78),
    [aux_sym_ret_token1] = ACTIONS(81),
    [anon_sym_HALT] = ACTIONS(84),
    [aux_sym_load_operation_token1] = ACTIONS(87),
    [aux_sym_store_operation_token1] = ACTIONS(90),
    [anon_sym_POP] = ACTIONS(93),
    [anon_sym_PUSH] = ACTIONS(93),
    [anon_sym_ADD] = ACTIONS(96),
    [anon_sym_ADC] = ACTIONS(96),
    [anon_sym_SUB] = ACTIONS(96),
    [anon_sym_SBC] = ACTIONS(96),
    [anon_sym_AND] = ACTIONS(96),
    [anon_sym_OR] = ACTIONS(96),
    [anon_sym_XOR] = ACTIONS(96),
    [anon_sym_SHL] = ACTIONS(96),
    [anon_sym_SHR] = ACTIONS(96),
    [anon_sym_ASHR] = ACTIONS(96),
    [anon_sym_ROTL] = ACTIONS(96),
    [anon_sym_ROTR] = ACTIONS(96),
  },
  [5] = {
    [sym__statement] = STATE(4),
    [sym_binary_operation] = STATE(4),
    [sym_compare] = STATE(4),
    [sym_move] = STATE(4),
    [sym_memory_operation] = STATE(4),
    [sym_control_operation] = STATE(4),
    [sym__preprocessor] = STATE(4),
    [sym_org] = STATE(4),
    [sym_define_memory] = STATE(4),
    [sym_equ] = STATE(4),
    [sym_jump] = STATE(26),
    [sym_jump_relative] = STATE(26),
    [sym_call] = STATE(26),
    [sym_ret] = STATE(26),
    [sym_halt] = STATE(26),
    [sym_load_operation] = STATE(27),
    [sym_store_operation] = STATE(27),
    [sym_stack_operation] = STATE(27),
    [sym_alu_mnemonic] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(99),
    [sym_label] = ACTIONS(5),
    [sym_comment] = ACTIONS(101),
    [anon_sym_CMP] = ACTIONS(9),
    [anon_sym_MOVE] = ACTIONS(11),
    [anon_sym_ORG] = ACTIONS(13),
    [aux_sym_define_memory_token1] = ACTIONS(15),
    [anon_sym_EQU] = ACTIONS(17),
    [anon_sym_JP] = ACTIONS(19),
    [anon_sym_JR] = ACTIONS(21),
    [anon_sym_CALL] = ACTIONS(23),
    [aux_sym_ret_token1] = ACTIONS(25),
    [anon_sym_HALT] = ACTIONS(27),
    [aux_sym_load_operation_token1] = ACTIONS(29),
    [aux_sym_store_operation_token1] = ACTIONS(31),
    [anon_sym_POP] = ACTIONS(33),
    [anon_sym_PUSH] = ACTIONS(33),
    [anon_sym_ADD] = ACTIONS(35),
    [anon_sym_ADC] = ACTIONS(35),
    [anon_sym_SUB] = ACTIONS(35),
    [anon_sym_SBC] = ACTIONS(35),
    [anon_sym_AND] = ACTIONS(35),
    [anon_sym_OR] = ACTIONS(35),
    [anon_sym_XOR] = ACTIONS(35),
    [anon_sym_SHL] = ACTIONS(35),
    [anon_sym_SHR] = ACTIONS(35),
    [anon_sym_ASHR] = ACTIONS(35),
    [anon_sym_ROTL] = ACTIONS(35),
    [anon_sym_ROTR] = ACTIONS(35),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(35), 1,
      anon_sym_OR,
    ACTIONS(103), 1,
      anon_sym_CMP,
    ACTIONS(105), 1,
      anon_sym_MOVE,
    ACTIONS(107), 1,
      anon_sym_ORG,
    ACTIONS(109), 1,
      aux_sym_define_memory_token1,
    ACTIONS(111), 1,
      anon_sym_EQU,
    ACTIONS(113), 1,
      anon_sym_JP,
    ACTIONS(115), 1,
      anon_sym_JR,
    ACTIONS(117), 1,
      anon_sym_CALL,
    ACTIONS(119), 1,
      aux_sym_ret_token1,
    ACTIONS(121), 1,
      anon_sym_HALT,
    ACTIONS(123), 1,
      aux_sym_load_operation_token1,
    ACTIONS(125), 1,
      aux_sym_store_operation_token1,
    STATE(54), 1,
      sym_alu_mnemonic,
    ACTIONS(127), 2,
      anon_sym_POP,
      anon_sym_PUSH,
    STATE(27), 3,
      sym_load_operation,
      sym_store_operation,
      sym_stack_operation,
    STATE(26), 5,
      sym_jump,
      sym_jump_relative,
      sym_call,
      sym_ret,
      sym_halt,
    STATE(28), 9,
      sym_binary_operation,
      sym_compare,
      sym_move,
      sym_memory_operation,
      sym_control_operation,
      sym__preprocessor,
      sym_org,
      sym_define_memory,
      sym_equ,
    ACTIONS(129), 11,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
  [83] = 2,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(133), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [122] = 2,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
    ACTIONS(137), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [159] = 4,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_numbers_repeat1,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(141), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [199] = 4,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_numbers_repeat1,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(147), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [239] = 4,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_numbers_repeat1,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(154), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [279] = 2,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(158), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [315] = 2,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(158), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [351] = 2,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(162), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [387] = 2,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(147), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [422] = 2,
    ACTIONS(164), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(166), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [457] = 2,
    ACTIONS(168), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(170), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [492] = 2,
    ACTIONS(168), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(170), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [527] = 2,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(174), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [561] = 2,
    ACTIONS(176), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(178), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [595] = 2,
    ACTIONS(180), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(182), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [629] = 2,
    ACTIONS(184), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(186), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [663] = 2,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(190), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [697] = 2,
    ACTIONS(192), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(194), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [731] = 2,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(198), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [765] = 2,
    ACTIONS(200), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(202), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [799] = 2,
    ACTIONS(204), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(206), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [833] = 2,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(210), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [867] = 2,
    ACTIONS(212), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(214), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [901] = 2,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(218), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [935] = 2,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(222), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [969] = 2,
    ACTIONS(224), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(226), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1003] = 2,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(230), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1037] = 2,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(234), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1071] = 8,
    ACTIONS(43), 1,
      anon_sym__N,
    ACTIONS(236), 1,
      sym_label,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_number,
    STATE(38), 1,
      sym_immediate,
    STATE(51), 1,
      sym_condition,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(41), 19,
      anon_sym__C,
      anon_sym__NC,
      anon_sym__V,
      anon_sym__NV,
      anon_sym__NN,
      anon_sym__M,
      anon_sym__P,
      anon_sym__Z,
      anon_sym__NZ,
      anon_sym__EQ,
      anon_sym__NE,
      anon_sym__ULE,
      anon_sym__UGT,
      anon_sym__ULT,
      anon_sym__UGE,
      anon_sym__SLE,
      anon_sym__SGT,
      anon_sym__SLT,
      anon_sym__SGE,
  [1117] = 2,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(244), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1151] = 8,
    ACTIONS(43), 1,
      anon_sym__N,
    ACTIONS(236), 1,
      sym_label,
    ACTIONS(246), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_number,
    STATE(43), 1,
      sym_immediate,
    STATE(52), 1,
      sym_condition,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(41), 19,
      anon_sym__C,
      anon_sym__NC,
      anon_sym__V,
      anon_sym__NV,
      anon_sym__NN,
      anon_sym__M,
      anon_sym__P,
      anon_sym__Z,
      anon_sym__NZ,
      anon_sym__EQ,
      anon_sym__NE,
      anon_sym__ULE,
      anon_sym__UGT,
      anon_sym__ULT,
      anon_sym__UGE,
      anon_sym__SLE,
      anon_sym__SGT,
      anon_sym__SLT,
      anon_sym__SGE,
  [1197] = 2,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(250), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1231] = 2,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(254), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1265] = 2,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(258), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1299] = 2,
    ACTIONS(260), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(262), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1333] = 2,
    ACTIONS(264), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(266), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1367] = 2,
    ACTIONS(268), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(270), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1401] = 2,
    ACTIONS(272), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(274), 27,
      anon_sym_CMP,
      anon_sym_MOVE,
      anon_sym_ORG,
      aux_sym_define_memory_token1,
      anon_sym_EQU,
      anon_sym_JP,
      anon_sym_JR,
      anon_sym_CALL,
      aux_sym_ret_token1,
      anon_sym_HALT,
      aux_sym_load_operation_token1,
      aux_sym_store_operation_token1,
      anon_sym_POP,
      anon_sym_PUSH,
      anon_sym_ADD,
      anon_sym_ADC,
      anon_sym_SUB,
      anon_sym_SBC,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_XOR,
      anon_sym_SHL,
      anon_sym_SHR,
      anon_sym_ASHR,
      anon_sym_ROTL,
      anon_sym_ROTR,
      sym_label,
  [1435] = 7,
    ACTIONS(43), 1,
      anon_sym__N,
    ACTIONS(236), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(40), 1,
      sym_immediate,
    STATE(53), 1,
      sym_condition,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(41), 19,
      anon_sym__C,
      anon_sym__NC,
      anon_sym__V,
      anon_sym__NV,
      anon_sym__NN,
      anon_sym__M,
      anon_sym__P,
      anon_sym__Z,
      anon_sym__NZ,
      anon_sym__EQ,
      anon_sym__NE,
      anon_sym__ULE,
      anon_sym__UGT,
      anon_sym__ULT,
      anon_sym__UGE,
      anon_sym__SLE,
      anon_sym__SGT,
      anon_sym__SLT,
      anon_sym__SGE,
  [1478] = 7,
    ACTIONS(276), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(17), 1,
      sym_register,
    STATE(18), 1,
      sym_immediate,
    STATE(77), 1,
      sym_src2,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(278), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1506] = 7,
    ACTIONS(276), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(17), 1,
      sym_register,
    STATE(18), 1,
      sym_immediate,
    STATE(73), 1,
      sym_src2,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(278), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1534] = 7,
    ACTIONS(276), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(17), 1,
      sym_register,
    STATE(18), 1,
      sym_immediate,
    STATE(39), 1,
      sym_src2,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(278), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1562] = 6,
    ACTIONS(276), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(71), 1,
      sym_register,
    STATE(80), 2,
      sym_reg_offset,
      sym_immediate,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(278), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1588] = 6,
    ACTIONS(276), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(71), 1,
      sym_register,
    STATE(82), 2,
      sym_reg_offset,
      sym_immediate,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
    ACTIONS(278), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1614] = 5,
    ACTIONS(236), 1,
      sym_label,
    ACTIONS(280), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_number,
    STATE(34), 1,
      sym_immediate,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1633] = 5,
    ACTIONS(236), 1,
      sym_label,
    ACTIONS(282), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_number,
    STATE(42), 1,
      sym_immediate,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1652] = 4,
    ACTIONS(236), 1,
      sym_label,
    STATE(12), 1,
      sym_number,
    STATE(41), 1,
      sym_immediate,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1668] = 3,
    STATE(75), 1,
      sym_register,
    STATE(86), 1,
      sym_src1,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1681] = 3,
    STATE(16), 1,
      sym_register,
    STATE(36), 1,
      sym_dest,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1694] = 3,
    STATE(9), 1,
      sym_number,
    STATE(33), 1,
      sym_numbers,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1707] = 3,
    STATE(75), 1,
      sym_register,
    STATE(87), 1,
      sym_src1,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1720] = 3,
    STATE(16), 1,
      sym_register,
    STATE(85), 1,
      sym_dest,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1733] = 3,
    STATE(16), 1,
      sym_register,
    STATE(21), 1,
      sym_dest,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1746] = 3,
    STATE(75), 1,
      sym_register,
    STATE(76), 1,
      sym_src1,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1759] = 2,
    STATE(20), 1,
      sym_number,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1769] = 2,
    STATE(15), 1,
      sym_number,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1779] = 2,
    STATE(78), 1,
      sym_register,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1789] = 2,
    STATE(29), 1,
      sym_register,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1799] = 2,
    STATE(88), 1,
      sym_number,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1809] = 2,
    STATE(74), 1,
      sym_register,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1819] = 2,
    STATE(72), 1,
      sym_register,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1829] = 2,
    STATE(32), 1,
      sym_number,
    ACTIONS(240), 4,
      sym_dec,
      sym_bin,
      sym_oct,
      sym_hex,
  [1839] = 2,
    STATE(81), 1,
      sym_register,
    ACTIONS(284), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1849] = 1,
    ACTIONS(286), 4,
      aux_sym_register_token1,
      anon_sym_SP,
      anon_sym_SR,
      anon_sym_PC,
  [1856] = 2,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    ACTIONS(290), 1,
      anon_sym_PLUS,
  [1863] = 1,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
  [1867] = 1,
    ACTIONS(294), 1,
      anon_sym_COMMA,
  [1871] = 1,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
  [1875] = 1,
    ACTIONS(298), 1,
      anon_sym_COMMA,
  [1879] = 1,
    ACTIONS(300), 1,
      anon_sym_COMMA,
  [1883] = 1,
    ACTIONS(302), 1,
      anon_sym_COMMA,
  [1887] = 1,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
  [1891] = 1,
    ACTIONS(306), 1,
      ts_builtin_sym_end,
  [1895] = 1,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
  [1899] = 1,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
  [1903] = 1,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
  [1907] = 1,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
  [1911] = 1,
    ACTIONS(316), 1,
      anon_sym_LPAREN,
  [1915] = 1,
    ACTIONS(318), 1,
      anon_sym_COMMA,
  [1919] = 1,
    ACTIONS(320), 1,
      anon_sym_COMMA,
  [1923] = 1,
    ACTIONS(322), 1,
      anon_sym_COMMA,
  [1927] = 1,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 83,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 159,
  [SMALL_STATE(10)] = 199,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 279,
  [SMALL_STATE(13)] = 315,
  [SMALL_STATE(14)] = 351,
  [SMALL_STATE(15)] = 387,
  [SMALL_STATE(16)] = 422,
  [SMALL_STATE(17)] = 457,
  [SMALL_STATE(18)] = 492,
  [SMALL_STATE(19)] = 527,
  [SMALL_STATE(20)] = 561,
  [SMALL_STATE(21)] = 595,
  [SMALL_STATE(22)] = 629,
  [SMALL_STATE(23)] = 663,
  [SMALL_STATE(24)] = 697,
  [SMALL_STATE(25)] = 731,
  [SMALL_STATE(26)] = 765,
  [SMALL_STATE(27)] = 799,
  [SMALL_STATE(28)] = 833,
  [SMALL_STATE(29)] = 867,
  [SMALL_STATE(30)] = 901,
  [SMALL_STATE(31)] = 935,
  [SMALL_STATE(32)] = 969,
  [SMALL_STATE(33)] = 1003,
  [SMALL_STATE(34)] = 1037,
  [SMALL_STATE(35)] = 1071,
  [SMALL_STATE(36)] = 1117,
  [SMALL_STATE(37)] = 1151,
  [SMALL_STATE(38)] = 1197,
  [SMALL_STATE(39)] = 1231,
  [SMALL_STATE(40)] = 1265,
  [SMALL_STATE(41)] = 1299,
  [SMALL_STATE(42)] = 1333,
  [SMALL_STATE(43)] = 1367,
  [SMALL_STATE(44)] = 1401,
  [SMALL_STATE(45)] = 1435,
  [SMALL_STATE(46)] = 1478,
  [SMALL_STATE(47)] = 1506,
  [SMALL_STATE(48)] = 1534,
  [SMALL_STATE(49)] = 1562,
  [SMALL_STATE(50)] = 1588,
  [SMALL_STATE(51)] = 1614,
  [SMALL_STATE(52)] = 1633,
  [SMALL_STATE(53)] = 1652,
  [SMALL_STATE(54)] = 1668,
  [SMALL_STATE(55)] = 1681,
  [SMALL_STATE(56)] = 1694,
  [SMALL_STATE(57)] = 1707,
  [SMALL_STATE(58)] = 1720,
  [SMALL_STATE(59)] = 1733,
  [SMALL_STATE(60)] = 1746,
  [SMALL_STATE(61)] = 1759,
  [SMALL_STATE(62)] = 1769,
  [SMALL_STATE(63)] = 1779,
  [SMALL_STATE(64)] = 1789,
  [SMALL_STATE(65)] = 1799,
  [SMALL_STATE(66)] = 1809,
  [SMALL_STATE(67)] = 1819,
  [SMALL_STATE(68)] = 1829,
  [SMALL_STATE(69)] = 1839,
  [SMALL_STATE(70)] = 1849,
  [SMALL_STATE(71)] = 1856,
  [SMALL_STATE(72)] = 1863,
  [SMALL_STATE(73)] = 1867,
  [SMALL_STATE(74)] = 1871,
  [SMALL_STATE(75)] = 1875,
  [SMALL_STATE(76)] = 1879,
  [SMALL_STATE(77)] = 1883,
  [SMALL_STATE(78)] = 1887,
  [SMALL_STATE(79)] = 1891,
  [SMALL_STATE(80)] = 1895,
  [SMALL_STATE(81)] = 1899,
  [SMALL_STATE(82)] = 1903,
  [SMALL_STATE(83)] = 1907,
  [SMALL_STATE(84)] = 1911,
  [SMALL_STATE(85)] = 1915,
  [SMALL_STATE(86)] = 1919,
  [SMALL_STATE(87)] = 1923,
  [SMALL_STATE(88)] = 1927,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ret, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ret, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_halt, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_halt, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(68),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(35),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(45),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(58),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(70),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_register, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_register, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numbers, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numbers, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_numbers_repeat1, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_numbers_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_numbers_repeat1, 2), SHIFT_REPEAT(62),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numbers, 2),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numbers, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_immediate, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_immediate, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dest, 1),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dest, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src2, 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_src2, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ret, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ret, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equ, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equ, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operation, 6),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operation, 6),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_store_operation, 6),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_store_operation, 6),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load_operation, 6),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_load_operation, 6),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 5),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 5),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_operation, 1),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control_operation, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory_operation, 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_memory_operation, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_operation, 2),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stack_operation, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 4),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 4),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_org, 2),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_org, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_memory, 2),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define_memory, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_move, 4),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_move, 4),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compare, 4),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compare, 4),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_relative, 2),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_relative, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_relative, 3),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_relative, 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_halt, 2),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_halt, 2),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [278] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alu_mnemonic, 1),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reg_offset, 1),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src1, 1),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [306] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reg_offset, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_frisc(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_label,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
